[package]
name = "advent-of-code-leaderboard"
version = "0.1.0"
authors = ["Andreas Runfalk <andreas@runfalk.se>"]
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.3"
chrono = "0.4"
chrono-tz = "0.5"
hyper = { version = "0.14", features = ["full"] }
structopt = "0.3"
dirs = "3"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
tower = "0.4"
